controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros_parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['FL_joint','BL_joint']
    right_wheel_names: ['FR_joint','BR_joint']
    wheel_separation: 0.3
    wheel_radius: 0.0625

    use_stamped_vel: false